/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items/{item_id}/mutations/transition/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Transition */
        post: operations["propose_transition_items__item_id__mutations_transition_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/mutations/description/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Description */
        post: operations["propose_description_items__item_id__mutations_description_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/mutations/attachment/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Attachment */
        post: operations["propose_attachment_items__item_id__mutations_attachment_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/mutations/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_items__item_id__mutations__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/mutations/{proposal_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Proposal */
        post: operations["confirm_proposal_items__item_id__mutations__proposal_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/mutations/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_items__item_id__mutations__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_items__item_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/conversation/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Thread */
        post: operations["start_thread_items__item_id__conversation_thread_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/conversation/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Drive one agent turn, streaming assistant text and tool events via SSE.
         *
         *     Event types emitted:
         *       - `delta` — assistant-text chunks (`{"text": "..."}`)
         *       - `message` — assistant or tool messages persisted during the turn
         *       - `proposal` — a staged mutation ready for confirmation (fired when the
         *         agent calls a mutating tool)
         *       - `done` — terminal, carries usage totals
         *       - `error` — terminal, carries a human-readable detail
         */
        post: operations["send_message_items__item_id__conversation_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/pinned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Pinned */
        get: operations["is_pinned_items__item_id__pinned_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin Item */
        post: operations["pin_item_items__item_id__pin_post"];
        /** Unpin Item */
        delete: operations["unpin_item_items__item_id__pin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pinned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pinned */
        get: operations["list_pinned_pinned_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Suggestion */
        post: operations["get_suggestion_items__item_id__suggestion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/suggestion/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage Suggestion */
        post: operations["stage_suggestion_items__item_id__suggestion_stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_items_get"];
        put?: never;
        /**
         * Create Item
         * @description Create a work item through the mutation pipeline.
         *
         *     With `dry_run=true`, returns a `ProposalDTO` the caller can preview. Without,
         *     executes the create and returns the stored result (still via
         *     `mutation_service.confirm`, so any provider-side validation runs).
         */
        post: operations["create_item_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comments */
        get: operations["get_comments_items__item_id__comments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/linked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Linked */
        get: operations["get_linked_items__item_id__linked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["list_prompts_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["get_prompt_prompts__key__get"];
        /** Put Prompt */
        put: operations["put_prompt_prompts__key__put"];
        post?: never;
        /**
         * Reset Prompt
         * @description Restore the canonical template.
         *
         *     The customized flag stays `True` because reset rewrites the file to the
         *     default rather than deleting it. Clients can distinguish by reading the
         *     content — the returned `content_md` is exactly the canonical template.
         */
        delete: operations["reset_prompt_prompts__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_settings_patch"];
        trace?: never;
    };
    "/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scopes */
        get: operations["list_scopes_scopes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Scope */
        get: operations["active_scope_scopes_active_get"];
        /** Set Active Scope */
        put: operations["set_active_scope_scopes_active_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Provider */
        get: operations["active_provider_providers_active_get"];
        /** Set Active Provider */
        put: operations["set_active_provider_providers_active_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Sync */
        post: operations["manual_sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/providers/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Types */
        get: operations["provider_types_setup_providers_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/test-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider */
        post: operations["test_provider_setup_test_provider_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/test-llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Llm */
        post: operations["test_llm_setup_test_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup Complete */
        post: operations["setup_complete_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttachmentDTO */
        AttachmentDTO: {
            /** Filename */
            filename: string;
            /** Url */
            url?: string | null;
        };
        /**
         * ChatRoleDTO
         * @description Mirrors the internal ChatMessage but flattens tool_calls so JSON
         *     consumers don't need to chase a union.
         */
        ChatRoleDTO: {
            /** Role */
            role: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Name */
            name?: string | null;
        };
        /** CommentDTO */
        CommentDTO: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Author */
            author: string;
            /** Body Md */
            body_md: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationDTO */
        ConversationDTO: {
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Tokens In
             * @default 0
             */
            tokens_in: number;
            /**
             * Tokens Out
             * @default 0
             */
            tokens_out: number;
            /**
             * Cost Cents
             * @default 0
             */
            cost_cents: number;
        };
        /** ConversationHistoryDTO */
        ConversationHistoryDTO: {
            conversation: components["schemas"]["ConversationDTO"] | null;
            /** Messages */
            messages: components["schemas"]["ChatRoleDTO"][];
        };
        /** CreateItemRequest */
        CreateItemRequest: {
            kind: components["schemas"]["ItemKind"];
            /** Title */
            title: string;
            /**
             * Description Md
             * @default
             */
            description_md: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Assignee */
            assignee?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDTO */
        HealthDTO: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ItemDTO */
        ItemDTO: {
            /** Id */
            id: string;
            kind: components["schemas"]["ItemKind"];
            /** Title */
            title: string;
            /** Description Md */
            description_md: string;
            state: components["schemas"]["ItemState"];
            /** Assignee */
            assignee?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Tags */
            tags?: string[];
            /** Updated At */
            updated_at?: string | null;
            /** Url */
            url?: string | null;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentDTO"][];
        };
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "epic" | "feature" | "story" | "task" | "bug";
        /**
         * ItemState
         * @enum {string}
         */
        ItemState: "new" | "active" | "blocked" | "needs_info" | "resolved" | "closed";
        /** MutationConfirmedDTO */
        MutationConfirmedDTO: {
            /** Proposal Id */
            proposal_id: string;
            /** Dry Run */
            dry_run: boolean;
            item?: components["schemas"]["ItemDTO"] | null;
            /** Attachment Url */
            attachment_url?: string | null;
        };
        /** PinnedStatusDTO */
        PinnedStatusDTO: {
            /** Item Id */
            item_id: string;
            /** Pinned */
            pinned: boolean;
        };
        /** PromptDTO */
        PromptDTO: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Filename */
            filename: string;
            /** Content Md */
            content_md: string;
            /** Customized */
            customized: boolean;
        };
        /** PromptSummaryDTO */
        PromptSummaryDTO: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Filename */
            filename: string;
            /** Customized */
            customized: boolean;
        };
        /** PromptUpdateRequest */
        PromptUpdateRequest: {
            /** Content Md */
            content_md: string;
        };
        /**
         * ProposalDTO
         * @description Typed proposal exposed to HTTP callers.
         *
         *     The `kind` discriminator matches the internal `Proposal.kind` strings; the
         *     remaining fields are flattened enough for a caller to render or preview
         *     without round-tripping to `render_diff` themselves (though we ship that
         *     pre-rendered for convenience).
         */
        ProposalDTO: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "state_change" | "description_patch" | "attachment_upload" | "item_create";
            /** Item Id */
            item_id?: string | null;
            /** Diff */
            diff: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ProposeAttachmentRequest */
        ProposeAttachmentRequest: {
            /** Filename */
            filename: string;
            /** Content Base64 */
            content_base64: string;
            /**
             * Content Type
             * @default text/markdown; charset=utf-8
             */
            content_type: string;
        };
        /** ProposeDescriptionRequest */
        ProposeDescriptionRequest: {
            /** New Description Md */
            new_description_md: string;
        };
        /** ProposeTransitionRequest */
        ProposeTransitionRequest: {
            intent: components["schemas"]["TransitionIntent"];
        };
        /** ProviderDTO */
        ProviderDTO: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Display Name */
            display_name: string;
            /** Scopes */
            scopes?: string[];
            /**
             * Active Scope
             * @default
             */
            active_scope: string;
            /**
             * Active
             * @default false
             */
            active: boolean;
        };
        /** ProviderSwitchRequest */
        ProviderSwitchRequest: {
            /** Key */
            key: string;
        };
        /** ScopeDTO */
        ScopeDTO: {
            /** Name */
            name: string;
            /**
             * Team
             * @default
             */
            team: string;
            /**
             * Area Path
             * @default
             */
            area_path: string;
            /**
             * Iteration Path
             * @default
             */
            iteration_path: string;
            /**
             * Assignee
             * @default @me
             */
            assignee: string;
            /**
             * Active
             * @default false
             */
            active: boolean;
        };
        /** ScopeSwitchRequest */
        ScopeSwitchRequest: {
            /** Name */
            name: string;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * SettingsDTO
         * @description Current config.toml, with secrets masked.
         *
         *     Shape mirrors `Config.model_dump()` exactly so the frontend can round-trip
         *     a deep-partial via `PATCH /settings`. The only transformation is that
         *     `http.token` comes back as `••••••••XXXX` (last four chars) when present.
         */
        SettingsDTO: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /**
         * SettingsPatchRequest
         * @description Deep-partial merge onto the current Config.
         *
         *     The frontend sends only the keys it wants to update. Values of `None` are
         *     treated as 'delete this key' — but in practice the frontend never needs to
         *     delete, so it's a Pydantic default we inherit from `exclude_unset`.
         */
        SettingsPatchRequest: {
            /** Patch */
            patch?: {
                [key: string]: unknown;
            };
        };
        /** SettingsUpdatedDTO */
        SettingsUpdatedDTO: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Requires Restart */
            requires_restart?: string[];
        };
        /** SetupCompleteDTO */
        SetupCompleteDTO: {
            /** Ok */
            ok: boolean;
            /** Config Path */
            config_path: string;
            /** Http Token */
            http_token: string;
            /**
             * Restart Required
             * @default true
             */
            restart_required: boolean;
            initial_sync?: components["schemas"]["SyncSummaryDTO"] | null;
        };
        /** SetupCompleteRequest */
        SetupCompleteRequest: {
            /** Providers */
            providers: {
                [key: string]: components["schemas"]["SetupProviderEntry"];
            };
            /** Active Provider */
            active_provider: string;
            llm?: components["schemas"]["SetupLlmEntry"] | null;
            /**
             * Http Bind
             * @default 0.0.0.0
             */
            http_bind: string;
            /**
             * Http Port
             * @default 8765
             */
            http_port: number;
            /**
             * Http Token
             * @default
             */
            http_token: string;
            /**
             * Telemetry Enabled
             * @default true
             */
            telemetry_enabled: boolean;
            /**
             * Run Initial Sync
             * @default true
             */
            run_initial_sync: boolean;
        };
        /** SetupLlmEntry */
        SetupLlmEntry: {
            /** Endpoint */
            endpoint: string;
            /** Api Key */
            api_key: string;
            /**
             * Deployment
             * @default gpt-5
             */
            deployment: string;
            /** Api Version */
            api_version?: string | null;
        };
        /** SetupProviderEntry */
        SetupProviderEntry: {
            /** Type */
            type: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Scope */
            scope?: {
                [key: string]: unknown;
            };
        };
        /**
         * SetupProviderFieldDTO
         * @description Describes one config field a provider type needs from the wizard.
         */
        SetupProviderFieldDTO: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @default string
             * @enum {string}
             */
            kind: "string" | "url" | "secret";
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Placeholder
             * @default
             */
            placeholder: string;
            /**
             * Help
             * @default
             */
            help: string;
        };
        /** SetupProviderTypeDTO */
        SetupProviderTypeDTO: {
            /** Id */
            id: string;
            /** Display */
            display: string;
            /** Requires Cli */
            requires_cli?: string[];
            /** Fields */
            fields?: components["schemas"]["SetupProviderFieldDTO"][];
        };
        /**
         * SetupStatusDTO
         * @description Probe endpoint the frontend hits to pick bootstrap vs normal mode.
         *
         *     Auth-free — the frontend needs to see this before it can decide whether to
         *     send the setup token or the real bearer token.
         */
        SetupStatusDTO: {
            /** Needs Setup */
            needs_setup: boolean;
            /** Config Path */
            config_path: string;
            /**
             * Providers Configured
             * @default 0
             */
            providers_configured: number;
            /**
             * Active Provider
             * @default
             */
            active_provider: string;
            /**
             * Llm Configured
             * @default false
             */
            llm_configured: boolean;
            /**
             * Http Configured
             * @default false
             */
            http_configured: boolean;
        };
        /** SetupTestLlmRequest */
        SetupTestLlmRequest: {
            /** Endpoint */
            endpoint: string;
            /** Api Key */
            api_key: string;
            /**
             * Deployment
             * @default gpt-5
             */
            deployment: string;
            /** Api Version */
            api_version?: string | null;
        };
        /** SetupTestProviderRequest */
        SetupTestProviderRequest: {
            /** Type */
            type: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /** SetupTestResultDTO */
        SetupTestResultDTO: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** StatusDTO */
        StatusDTO: {
            /** Provider Key */
            provider_key: string;
            /** Provider Display */
            provider_display: string;
            /** Scope Key */
            scope_key: string;
            /** Read Only */
            read_only: boolean;
            /** Chat Enabled */
            chat_enabled: boolean;
            /** Last Sync At */
            last_sync_at?: string | null;
            /**
             * Offline
             * @default false
             */
            offline: boolean;
            /**
             * Pending Proposals
             * @default 0
             */
            pending_proposals: number;
        };
        /** SuggestionDTO */
        SuggestionDTO: {
            /** Item Id */
            item_id: string;
            intent: components["schemas"]["TransitionIntent"];
            /**
             * Description Patch Md
             * @default
             */
            description_patch_md: string;
            /** Open Questions */
            open_questions?: string[];
        };
        /** SuggestionStageRequest */
        SuggestionStageRequest: {
            intent: components["schemas"]["TransitionIntent"];
            /**
             * Description Patch Md
             * @default
             */
            description_patch_md: string;
        };
        /** SyncSummaryDTO */
        SyncSummaryDTO: {
            /** Upserted */
            upserted: number;
            /** Archived */
            archived: number;
            /** Watermark */
            watermark?: string | null;
            /**
             * Offline
             * @default false
             */
            offline: boolean;
        };
        /**
         * TransitionIntent
         * @enum {string}
         */
        TransitionIntent: "start_work" | "pause" | "block" | "needs_info" | "close_done" | "close_wontfix" | "reopen";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    propose_transition_items__item_id__mutations_transition_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_description_items__item_id__mutations_description_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_attachment_items__item_id__mutations_attachment_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeAttachmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_items__item_id__mutations__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_proposal_items__item_id__mutations__proposal_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationConfirmedDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_items__item_id__mutations__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_items__item_id__conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationHistoryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_thread_items__item_id__conversation_thread_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_items__item_id__conversation_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    is_pinned_items__item_id__pinned_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedStatusDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pin_item_items__item_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_item_items__item_id__pin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pinned_pinned_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDTO"][];
                };
            };
        };
    };
    get_suggestion_items__item_id__suggestion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_suggestion_items__item_id__suggestion_stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionStageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_items_get: {
        parameters: {
            query?: {
                /** @description Filter by item kind. */
                kind?: components["schemas"]["ItemKind"] | null;
                /** @description Filter by item state. Repeat to union (e.g. ?state=active&state=blocked). */
                state?: components["schemas"]["ItemState"][] | null;
                /** @description Filter to items that carry this tag/label. */
                tag?: string | null;
                archived?: boolean;
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_items_post: {
        parameters: {
            query?: {
                /** @description Return the proposal without creating. */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDTO"] | components["schemas"]["MutationConfirmedDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comments_items__item_id__comments_get: {
        parameters: {
            query?: {
                /** @description Fetch fresh from provider. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_linked_items__item_id__linked_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_items__item_id__get: {
        parameters: {
            query?: {
                /** @description Fetch from provider instead of cache. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptSummaryDTO"][];
                };
            };
        };
    };
    get_prompt_prompts__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_prompt_prompts__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_prompt_prompts__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDTO"];
                };
            };
        };
    };
    patch_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdatedDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scopes_scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeDTO"][];
                };
            };
        };
    };
    active_scope_scopes_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeDTO"];
                };
            };
        };
    };
    set_active_scope_scopes_active_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDTO"][];
                };
            };
        };
    };
    active_provider_providers_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDTO"];
                };
            };
        };
    };
    set_active_provider_providers_active_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_sync_sync_post: {
        parameters: {
            query?: {
                /** @description Reset watermark before syncing. */
                full?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSummaryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDTO"];
                };
            };
        };
    };
    setup_status_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusDTO"];
                };
            };
        };
    };
    provider_types_setup_providers_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupProviderTypeDTO"][];
                };
            };
        };
    };
    test_provider_setup_test_provider_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupTestProviderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupTestResultDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_setup_test_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupTestLlmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupTestResultDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_complete_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupCompleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupCompleteDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    whoami_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
