"""Pydantic DTOs exposed over the HTTP surface.

Converted from the internal dataclasses so the HTTP contract is decoupled
from on-disk / in-memory representations. Only fields useful to a headless
API caller are exposed — `provider_raw` for example is deliberately omitted
since it leaks Azure DevOps-specific shape.

Split into submodules by route group (`core`, `mutations`, `routes`,
`setup`). Callers should import from `docket.api.schemas` and let this
package re-export; submodule imports are fine too."""

from __future__ import annotations

from docket.api.schemas.core import (
    AnswerQuestionRequest,
    AttachmentDTO,
    ChatRoleDTO,
    CommentDTO,
    ConversationDTO,
    ConversationHistoryDTO,
    CreateItemRequest,
    HealthDTO,
    ItemDTO,
    QuestionAnswerDTO,
    QuestionDTO,
    QuestionItemDTO,
    QuestionOptionDTO,
    SendMessageRequest,
    StatusDTO,
    UsageDTO,
)
from docket.api.schemas.mutations import (
    MutationConfirmedDTO,
    ProposalDTO,
    ProposeAttachmentRequest,
    ProposeCommentRequest,
    ProposeDescriptionRequest,
    ProposeTransitionRequest,
)
from docket.api.schemas.routes import (
    MCPPresetApplyRequest,
    MCPPresetDTO,
    MCPPresetEnvDTO,
    MCPPresetListDTO,
    MCPRuntimeDTO,
    MCPRuntimeServerDTO,
    MCPServerDTO,
    MCPServerListDTO,
    MCPServerTestResultDTO,
    MCPServerUpdateRequest,
    MCPToolDTO,
    MemoryCreateRequest,
    MemoryDTO,
    MemoryListDTO,
    MemoryUpdateRequest,
    PinnedStatusDTO,
    ProjectDTO,
    ProjectUpdateRequest,
    PromptDTO,
    PromptSummaryDTO,
    PromptUpdateRequest,
    ProviderDTO,
    ProviderSwitchRequest,
    ScopeDTO,
    ScopeSwitchRequest,
    SettingsDTO,
    SettingsHttpTokenDTO,
    SettingsLlmKeyDTO,
    SettingsLlmKeyRequest,
    SettingsPatchRequest,
    SettingsProviderAddRequest,
    SettingsProviderUpdateRequest,
    SettingsUpdatedDTO,
    SourceCreateRequest,
    SourceDTO,
    SourceListDTO,
    SourceUpdateRequest,
    SuggestionDTO,
    SuggestionStageRequest,
    SyncSummaryDTO,
)
from docket.api.schemas.setup import (
    CliStatusDTO,
    CliToolStatusDTO,
    DiscoverRequest,
    DiscoverResultDTO,
    DiscoveryItemDTO,
    GithubHostDTO,
    ProbeScopeDTO,
    ProbeScopeRequest,
    SetupCompleteDTO,
    SetupCompleteRequest,
    SetupLlmEntry,
    SetupProviderEntry,
    SetupProviderFieldDTO,
    SetupProviderTypeDTO,
    SetupStatusDTO,
    SetupTestLlmRequest,
    SetupTestProviderRequest,
    SetupTestResultDTO,
    SuggestKeyDTO,
    SuggestKeyRequest,
    SuggestLabelDTO,
    SuggestLabelRequest,
)

__all__ = [
    "AnswerQuestionRequest",
    "AttachmentDTO",
    "ChatRoleDTO",
    "CliStatusDTO",
    "CliToolStatusDTO",
    "CommentDTO",
    "ConversationDTO",
    "ConversationHistoryDTO",
    "CreateItemRequest",
    "DiscoverRequest",
    "DiscoverResultDTO",
    "DiscoveryItemDTO",
    "GithubHostDTO",
    "HealthDTO",
    "ItemDTO",
    "MCPPresetApplyRequest",
    "MCPPresetDTO",
    "MCPPresetEnvDTO",
    "MCPPresetListDTO",
    "MCPRuntimeDTO",
    "MCPRuntimeServerDTO",
    "MCPServerDTO",
    "MCPServerListDTO",
    "MCPServerTestResultDTO",
    "MCPServerUpdateRequest",
    "MCPToolDTO",
    "MemoryCreateRequest",
    "MemoryDTO",
    "MemoryListDTO",
    "MemoryUpdateRequest",
    "MutationConfirmedDTO",
    "PinnedStatusDTO",
    "ProbeScopeDTO",
    "ProbeScopeRequest",
    "ProjectDTO",
    "ProjectUpdateRequest",
    "PromptDTO",
    "PromptSummaryDTO",
    "PromptUpdateRequest",
    "ProposalDTO",
    "ProposeAttachmentRequest",
    "ProposeCommentRequest",
    "ProposeDescriptionRequest",
    "ProposeTransitionRequest",
    "ProviderDTO",
    "ProviderSwitchRequest",
    "QuestionAnswerDTO",
    "QuestionDTO",
    "QuestionItemDTO",
    "QuestionOptionDTO",
    "ScopeDTO",
    "ScopeSwitchRequest",
    "SendMessageRequest",
    "SettingsDTO",
    "SettingsHttpTokenDTO",
    "SettingsLlmKeyDTO",
    "SettingsLlmKeyRequest",
    "SettingsPatchRequest",
    "SettingsProviderAddRequest",
    "SettingsProviderUpdateRequest",
    "SettingsUpdatedDTO",
    "SetupCompleteDTO",
    "SetupCompleteRequest",
    "SetupLlmEntry",
    "SetupProviderEntry",
    "SetupProviderFieldDTO",
    "SetupProviderTypeDTO",
    "SetupStatusDTO",
    "SetupTestLlmRequest",
    "SetupTestProviderRequest",
    "SetupTestResultDTO",
    "SourceCreateRequest",
    "SourceDTO",
    "SourceListDTO",
    "SourceUpdateRequest",
    "StatusDTO",
    "SuggestKeyDTO",
    "SuggestKeyRequest",
    "SuggestLabelDTO",
    "SuggestLabelRequest",
    "SuggestionDTO",
    "SuggestionStageRequest",
    "SyncSummaryDTO",
    "UsageDTO",
]
